# Generated by Django 4.2.16 on 2024-10-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5),
        ),
    ]
