# Generated by Django 4.2.16 on 2024-10-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_game_result_alter_game_player2_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='journal_entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
