# Generated by Django 4.2.16 on 2024-10-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_game_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moves_count',
            field=models.IntegerField(default=0),
        ),
    ]
